name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildtype: [release, debug]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/setup
        with:
          buildtype: ${{ matrix.buildtype }}
