name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            buildtype: Release
          - os: ubuntu-latest
            buildtype: Debug
          - os: windows-latest
            buildtype: Release
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build (${{ matrix.os }} / ${{ matrix.buildtype }})
        uses: ./.github/actions/setup
        with:
          buildtype: ${{ matrix.buildtype }}
